# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-10 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_auto_20180609_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='flat',
            field=models.IntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='home',
            field=models.CharField(max_length=9999, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='indx',
            field=models.IntegerField(max_length=6, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Регион проживания'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='sity',
            field=models.CharField(max_length=50, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(max_length=256, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type_contact',
            field=models.IntegerField(choices=[(0, 'phone'), (1, 'e-mail')], verbose_name='Тип контакта (телефон / e-mail)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс денег'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
