# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20180610_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.AddField(
            model_name='worker',
            name='otdel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workers.Otdel'),
        ),
    ]
