# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_auto_20180703_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='otdel',
        ),
        migrations.DeleteModel(
            name='Otdel',
        ),
    ]
