# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_worker_otdel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='indx',
            field=models.IntegerField(verbose_name='Индекс'),
        ),
    ]
