# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardwork', '0003_auto_20180609_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indx', models.IntegerField(max_length=6)),
                ('region', models.CharField(max_length=50)),
                ('sity', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('home', models.IntegerField(max_length=9999)),
                ('flat', models.IntegerField(max_length=9999)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwork.Worker')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='id_worker',
            new_name='worker',
        ),
    ]
