# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwork', '0005_auto_20180609_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
